### PR TITLE
Logging exposure

### PR DESCRIPTION
**Pull request by GregBowyer**
Some changes to make it easier to log in CMPH, and to expose the logger to python.

There are two global variables with static TU life-cycle here, I don't think they are really that bad since logging is generally a global concern.

The first one is the CMPH generic `cmph_logger` variable. That one is exposed for cmph and I think we should try to get most of those changes (9f26537) upstream to the CMPH project.

The second is specific to python bindings, its a round the houses way of dealing with `va_list` as that has compiler specific semantics that CFFI cannot generate ABI stubs for.  As such we need to get a python function down to CMPH as a callback, but cannot go direct (hence the slightly irritating `_py_log`.

Fortunately both of these symbols should only express within the TU anyhow.

@venkateshks @Zarkantho thoughts ?

### CODE REVIEW

**Comment by venkateshks** [comment]
LGTM

**Comment by venkateshks** [comment]
@GregBowyer 
Right now the C code is essentially single threaded, and more over for python-cffi will be under a GIT. Is there something that I am missing about your concerns on cmph_logger being within a TU.
One check which perhaps will be useful is to check if the logger being passed is compatible and throw a proper error if not.
The changes LGTM

**Comment by venkateshks** [comment]
@GregBowyer Now I am wondering about the TU. Will the cmph_logger.logger be set in all the .c files?

**Comment by GregBowyer** [comment]
Should be, I wasnt worried about it, actually the opposite, I was glad that the global was not leaking out

**Comment by GregBowyer** [comment]
FYI I merged this and a bunch of the other pull requests so I am going to close this given that you didnt spot anything scary

**Pull request closed without merging**
